### ISSUE TITLE
Fox Paper - Myōbu

### ISSUE THREAD

**Issue by kirito-m** [Myobu-Guardians/realm#10]
## 🦊 Introduction

**The whitepaper will keep getting updated.**

Myōbu ([命婦](https://en.wikipedia.org/wiki/My%C5%8Dbu)) is a celestial fox spirit with white fur and full, fluffy tails reminiscent of ripe grain. They are holy creatures and bring happiness and blessings to those around them.

![Myōbu](https://user-images.githubusercontent.com/111298477/201519685-f3d80e33-21d1-4779-a8e9-950a78fb8a82.png)

They are also known as the "Fox of Happiness" and "Fox of Good Fortune". Myōbu is often depicted with a large, full moon in the background and is often seen in the company of the sun goddess [Amaterasu](https://en.wikipedia.org/wiki/Amaterasu).

![Amaterasu_cave](https://user-images.githubusercontent.com/111298477/201519651-db99befb-b238-4184-b003-f4ff84ddb6a2.jpeg)

*Amaterasu emerges from the Heavenly Rock Cave (Shunsai Toshimasa, 1887)*

Myōbu is an ERC20-compliant token launched on ERC and BNB networks in 2021. It is a token that will always survive.  

Myōbu is a decentralized token that is governed entirely by the community.

* Token Name: Myōbu - $MYOBU
* Token Networks:
    * ETH: [0xDfDd3459D4F87234751696840092ee20C970Fb07](https://etherscan.io/token/0xDfDd3459D4F87234751696840092ee20C970Fb07)
    * BNB: [0x4Ef06d1A55962f29D362c53c864a4f0c791DcB9E](https://bscscan.com/token/0x4Ef06d1A55962f29D362c53c864a4f0c791DcB9E)
* Development Fees:
    It charges a certain amount of tax on every transaction. The Myōbu team will use the tax for marketing, project development, CEX listings, buybacks, staking rewards, etc.
    * BUYS: 0% currently (max 5%)
    * SELLS: 5% currently (max 5%)
* Tax distributions:
    50% to the team wallet for marketing, project development, etc.
    50% to the Myōbu staking contract.  

## Mission

Our team aims to build serious products with real-life utilities that could benefit the web3 world and individuals' lives. 

We are a team of developers, designers, and marketers passionate about blockchain technology. We are also a community of crypto enthusiasts building projects that could bring value to the community.

## Products

Our products involve the DeFi space, NFTs, social media, and gaming.

### Myōbu Protocol

* Website https://protocol.myobu.io/ (Released, still in development)
* Source code
   * [myobu-protocol-client](https://github.com/Myobu-Guardians/myobu-protocol-client) 
   * [NPM package](https://www.npmjs.com/package/myobu-protocol-client)

[![Protocol](https://user-images.githubusercontent.com/111298477/201521255-0d20905f-5498-44b8-8188-d5071ffed50f.png)](https://protocol.myobu.io/#/db)

Myōbu Protocol is our **core** product. Many of our other products, such [MNS](https://protocol.myobu.io/#/mns), [Realm](https://realm.myobu.io/), are/will be built on top of it. 
Myōbu Protocol aims to solve the problem of high gas fees on blockchain networks. We built a protocol layer that:

* Authenticates users by simply signing a message with their wallet. This guarantees that Myōbu Protocol works on any blockchain network and users don't need to pay gas fees to interact with the protocol.
* Allows users to store/query data on our Myōbu Database (a decentralized graph database built on the [Neo4j](https://neo4j.com/) ) without paying gas fees. This feature also enables users to perform complicated queries on the database, which cannot be directly done with smart contracts on blockchain.  
* Allows PubSub messages to be sent to users without paying gas fees. This feature is useful for building real-time applications on the blockchain.
* Allows arbitrary NFT metadata to be stored on our Myōbu Database and will enable users to mint NFTs only when they want to.

### MNS (Myōbu Name Service)

* Website https://protocol.myobu.io/#/mns/ (Released)

[![MNS](https://user-images.githubusercontent.com/111298477/201521276-f838b918-50f7-4250-b91b-c3553f053a09.png)](https://protocol.myobu.io/#/mns)

MNS is a decentralized name service built on top of the Myōbu Protocol. It allows users to register a name for their wallet address. Many of our products will use MNS to identify users.

### Realm 界

* Website  https://realm.myobu.io/ (Released, still in development)
* Source code
    * [realm](https://github.com/Myobu-Guardians/realm)

[![Realm](https://user-images.githubusercontent.com/111298477/201521306-df72e594-ea33-4f4e-bb26-7ec2186bfe32.png)](https://realm.myobu.io/)
    
Realm is a decentralized social network and DAO built on Myōbu Protocol and MNS. It allows users to create their social network and invite their friends to join. Users can post notes on Realm to share their thoughts and ideas, make proposals, and vote on proposals.

Realm will also be the web3 version of Steam, where third parties can create their games and publish/sell them on Realm. We will also allow users to trade NFTs on Realm.

Realm will also have a friend system and support address-to-address messaging, allowing users to send instantaneous messages and in-game chat.  

Realm will also allow game developers to embed Realm into their games, allowing users to play games with their friends on Realm, allowing in-game chats, and allowing users to trade NFTs in-game.

Realm will also have more possible features to be implemented, such as

* Send tokens to other users
* Invite more people by mail or wallet address
* News section from Cointelegraph or others
* Saved posts
* Trending posts
* Online/Offline mode
* etc...

#### Hikari 光

* Website https://hikari-sandbox.myobu.io/ (Beta)
*  Source code
    * [hikari-dev](https://github.com/Myobu-Guardians/hikari-dev)

[![Hikari](https://user-images.githubusercontent.com/111298477/201520965-ff439bbe-24d7-4bbd-b7cf-f9aa64cd6cd1.jpeg)](http://hikari-sandbox.myobu.io/)

Hikari is a competitive trading card game. We have released a beta version of Hikari, and we will integrate it with Realm. Hikari will be the first game published on Realm. We will support sponsored tournaments and prize pools for Hikari. We will also support in-game NFT trading.

#### Katana 刀
(Planned, Q1 2023)

![Katana](https://user-images.githubusercontent.com/111298477/201521143-bc13bc3d-de7e-413f-bff8-790df4670493.jpg)

Katana will be a hard-core roguelike adventure game.
There will be a free initial NFT to start to play and more advanced with unique features that cost Myōbu.

#### Yume 夢
(Planned starts develop at 50 M Market cap)

[![Yume](https://user-images.githubusercontent.com/111298477/201521102-de69edb3-926e-4996-80ea-e9184109a441.jpg)](https://www.youtube.com/watch?v=YnDV7rXUFBU&t=1s&ab_channel=MyobuOfficial)

Yume will be a high-fidelity open-world MMORPG metaverse powered by Unreal Engine 5.
The main focus will be to engage the Myōbu community.
Myōbu will be part of the game tokenomics.

### Myōbu Staking

* Website: https://myobu.io/#/staking

[![Staking](https://user-images.githubusercontent.com/111298477/201521193-d36eaaea-2fcd-4187-bdaa-f077931a2dec.png)](https://myobu.io/#/staking)

Myōbu Staking is a staking platform that allows users to stake their Myōbu tokens and earn ETH (or BNB) rewards. 

The next step is to develop the staking purpose of the Myōbu ecosystem. The number of tokens staked will determine:

- The amount of rewards users can earn.
- The number of voting power users have.
- The Myōbu Protocol services users can access.
- The voting power in the future DAO

### (New) Myōbu NFT Collection

The MYOBU NFT Collection will allow holders to bust Myōbu staking and will be a multiplier for your vote power in future DAO. Also, the purpose of this collection is to decrease the supply of Myōbu and collect funds for marketing or listing purposes.

## Events

* Fox Pit (Paused)
* Fountain of Fortune (Paused)
*  Sponsored game hackathon (Planned)
*  Sponsored game tournament (Planned)

## Roadmap

Accomplished Milestones:  
* [x] Staking Contract with ETH rewards on Ethereum Blockchain
* [x] Staking Contract with BNB rewards on Binance Chain Blockchain
* [x] Bridge between MYOBU ERC-20 token and MYOBU BSC token

Q3 2022

* [x] Launch Myōbu Protocol
* [x] Launch MNS (Myōbu Name Service)
* [x] Launch Myōbu Realm (the initial version)
* [x] Launch Hikari Beta

Q4 2022
* [ ] [myobu.io](https://myobu.io/#/) website update
* [ ] Launch the Myōbu Realm - Friend System
* [ ] Launch the Myōbu Realm - Proposal & Vote System
* [ ] Launch the Myōbu Realm - Game Store
* [ ] Publish Hikari on the Myōbu Realm - Game Store
* [ ] Publish Hikari NFT card packs on the Myōbu Realm - Game Store

2023
* [ ] Improve existing products, such as Myōbu Protocol, MNS, Realm, etc.
* [ ] Develop the new game project - Katana 刀
* [ ] More trading pairs and more networks support
* [ ] More CEXs listings
* [ ] More marketing and community building
* [ ] DAO governance on Realm
* [ ] Game Hackathon events
* [ ] Hikari tournament (and other game tournaments)

## Social media links
* [Website](https://myobu.io/) 
* [Telegram](https://t.me/MyobuOfficial) 
* [Twitter](https://twitter.com/MyobuOfficial) 
* [GitHub](https://github.com/myobu-guardians) 
* [Discord](https://discord.gg/kxCuVdZwPn) 
* [Instagram](https://www.instagram.com/myobu_official/) 
* [Medium](https://myobu.medium.com/) 
* [YouTube](https://www.youtube.com/channel/UCkEdaRw8w0daEvGgzKff8TA/videos)

## Contract Addresses

* MYOBU Token
  * ETH [0xDfDd3459D4F87234751696840092ee20C970Fb07](https://etherscan.io/token/0xDfDd3459D4F87234751696840092ee20C970Fb07) 
  * BNB [0x4Ef06d1A55962f29D362c53c864a4f0c791DcB9E](https://bscscan.com/token/0x4Ef06d1A55962f29D362c53c864a4f0c791DcB9E) 
* MyobuDistributor
  * ETH [0x27de51d4c321dcb3d3ad6c8f4db7dd8fbbc10b67](https://etherscan.io/address/0x27de51d4c321dcb3d3ad6c8f4db7dd8fbbc10b67)
  * BNB [0x9f82c3c2F3f6DBFACc64095Af62f835F1C1baAC1](https://bscscan.com/address/0x9f82c3c2f3f6dbfacc64095af62f835f1c1baac1)
* Multisig Team Wallet
  * ETH [0x6f5ffb9FDe0b5F2D8Fda3346AC67FAbE481F6D9b](https://etherscan.io/address/0x6f5ffb9FDe0b5F2D8Fda3346AC67FAbE481F6D9b)
  * BNB [0x2BBcDe842EFdC70Ee582bcfEd4D5E0bA47E6FE9A](https://bscscan.com/address/0x2BBcDe842EFdC70Ee582bcfEd4D5E0bA47E6FE9A)
* Staking contract
  * ETH [0x3CC2E70A24D116E939FB101d84Af40Bb5BbD4c53](https://etherscan.io/address/0x3CC2E70A24D116E939FB101d84Af40Bb5BbD4c53)
  * BNB [0x2fdceabdd77423dfa7ff06eea7fbeab5f4b74a0e](https://bscscan.com/address/0x2fdceabdd77423dfa7ff06eea7fbeab5f4b74a0e)

## Exchanges

* DEX
  * [Uniswap ETH-MYOBU](https://app.uniswap.org/#/swap?use=V2&inputCurrency=ETH&outputCurrency=0xdfdd3459d4f87234751696840092ee20c970fb07)
  * [Pancakeswap BNB-MYOBU](https://pancakeswap.finance/swap?outputCurrency=0x4ef06d1a55962f29d362c53c864a4f0c791dcb9e)
* CEX
  * [Hotbit](https://www.hotbit.io/exchange?symbol=MYOBU_USDT)
* Fiat
  * [Routely](https://buy.routelay.com/?primaryColor=9075f9&mode=buy&isDarkTheme=false&cl=myobu)

## Bridge

You can bridge the MYOBU token from Ethereum to the BNB chain and the other way around on [Multichain](https://app.multichain.org/#/router).

## Audit report

[CTDSec](https://ctdsec.com/) audited our token contract. The report is available [here](https://myobu.io/files/Cybersecurity_Audit_CTDSEC_MyobuDAOv2.pdf).
